# Question 1

In [4]:
#Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
import numpy as np

vect = np.random.randint(low=0, high=11, size=5)
print(vect)

[ 9 10  1  2  7]


# Question2

In [5]:
#Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values​​except the first and last.

vector = np.arange(15, 56)
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


# QUESTION 3

In [6]:
#Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.

# Create random array with 1000 elements
array = np.random.rand(1000)

# Compute average, variance, and standard deviation
average = np.mean(array)
variance = np.var(array)
std_dev = np.std(array)

In [7]:
# Print results
print("Average: ", average)
print("Variance: ", variance)
print("Standard Deviation: ", std_dev)

Average:  0.47948533897449247
Variance:  0.07996836316331399
Standard Deviation:  0.2827867803899503


# Question 4

In [9]:
#Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array. 

# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Calculate cumulative sum along axis 0 (columns)
cum_sum_axis_0 = np.cumsum(arr, axis=0)

# Calculate cumulative sum along axis 1 (rows)
cum_sum_axis_1 = np.cumsum(arr, axis=1)

# Sum over rows for each of the 3 columns
sum_columns = np.sum(arr, axis=0)

# Sum over columns for each of the 2 rows
sum_rows = np.sum(arr, axis=1)

In [10]:
# Print results
print("Cumulative Sum along axis 0:\n", cum_sum_axis_0)
print("Cumulative Sum along axis 1:\n", cum_sum_axis_1)
print("Sum over Rows for each of the 3 Columns:", sum_columns)
print("Sum over Columns for each of the 2 Rows:", sum_rows)

Cumulative Sum along axis 0:
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
Cumulative Sum along axis 1:
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
Sum over Rows for each of the 3 Columns: [12 15 18]
Sum over Columns for each of the 2 Rows: [ 6 15 24]


# Question 5

In [11]:
#Write a NumPy program to compute the multiplication of two given matrixes.

# Create first matrix with shape (2, 3)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create second matrix with shape (3, 2)
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Compute multiplication of two matrices
C = np.dot(A, B)

In [14]:
# Print result
print("Resultant Matrix:\n", C)

Resultant Matrix:
 [[ 58  64]
 [139 154]]
