In [22]:
#Use the zeros and ones functions of NumPy to form the table below

import numpy as np

In [23]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [24]:
ones = np.ones((3),dtype=int)
ones

array([1, 1, 1])

In [14]:
K= np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])
K

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])